#!/usr/bin/env php
<?php

define('ROOT_DIR', __DIR__);
define('STORAGE_DIR', __DIR__ . '/app/storage');

require __DIR__ . '/vendor/autoload.php';

$app = Anano\App::init();

if (count($argv) > 1)
{
    new Anano\Console( array_slice($argv, 1) );
}
else
{
    echo <<<HEREDOC
======================================================================
Anano command line interface

Type run <command>
----------------------------------------------------------------------
Available commands:
    migrate:up
    migrate:down
    migrate:reload
    migrate:make <name>
    
    command:make <name>
    
    hash <password>
    
    clearcache
======================================================================
HEREDOC;
}