#!/usr/bin/env php
<?php

define('ROOT_DIR', __DIR__);
define('STORAGE_DIR', __DIR__ . '/app/storage');

require __DIR__ . '/vendor/autoload.php';
$config = require __DIR__ . '/app/config/console.php';

use Anano\Console\Router;
use Anano\Console\Arguments;

$app = Anano\App::init();
$router = new Router( new Arguments($argv), $config );
$res = $router->dispatch();
echo $res->getMessage();
exit($res->getCode());